<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCjzee20\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCjzee20/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCjzee20.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCjzee20\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCjzee20\appProdProjectContainer([
    'container.build_hash' => 'Cjzee20',
    'container.build_id' => '7eacc2dd',
    'container.build_time' => 1658576439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCjzee20');
