<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZnchdbc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZnchdbc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZnchdbc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZnchdbc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZnchdbc\appProdProjectContainer([
    'container.build_hash' => 'Znchdbc',
    'container.build_id' => 'befca00d',
    'container.build_time' => 1658575636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZnchdbc');
