<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG28kelb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG28kelb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG28kelb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerG28kelb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerG28kelb\appDevDebugProjectContainer([
    'container.build_hash' => 'G28kelb',
    'container.build_id' => 'd545615e',
    'container.build_time' => 1660250020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG28kelb');
