<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHhxd1g8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHhxd1g8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHhxd1g8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHhxd1g8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHhxd1g8\appDevDebugProjectContainer([
    'container.build_hash' => 'Hhxd1g8',
    'container.build_id' => 'c7372329',
    'container.build_time' => 1660256143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHhxd1g8');
